# Generated by Django 3.0 on 2019-12-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(help_text='Resolution 1920x805', upload_to='slides')),
                ('url', models.URLField(blank=True, help_text='It will add Shop Now button with provided link', null=True)),
            ],
        ),
    ]
